include:
  - project: acc-co/devops/python/acc-py-gitlab-ci-templates
    file: v2/python.gitlab-ci.yml

variables:
  PY_VERSION: "3.7"
  ACC_PY_BASE_IMAGE_TAG: '2020.11'
  project_package: cernml.loops
  project_name: cernml-coi-loops

# Build: Create a wheel to speed up installation.

build_sdist:
  extends: .acc_py_build_sdist

build_wheel:
  extends: .acc_py_build_wheel

# Test: Run linters and unit tests. Run tests both in-tree and out-of-tree.

test_lint:
  extends:
    - .acc_py_dev_test
  stage: test
  before_script:
    - !reference [.acc_py_dev_test, before_script]
    - python -m pip install
      -e ${project_root}[lint]
  script:
    - cd ${project_root}
    - ./run_linters.sh ./src

test_dev:
  extends: .acc_py_dev_test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  # Override `script` to change the precise pytest-cov arguments.
  script:
    - cd ${project_root}
    - python -m pytest
      --cov=./src
      --cov-branch
      --cov-report=term
      --cov-report=html:coverage-html
      --cov-report=xml:coverage-report.xml
      --junitxml=junit-report.xml

test_examples:
  extends:
    - .acc_py_run_on_manylinux_py_version
  before_script:
    - !reference [.acc_py_run_on_manylinux_py_version, before_script]
    - python -m pip install
      -e ${project_root}[examples]
  script:
    - cd ${project_root}/examples
    - python simple.py -n10
    - python comparison.py -n1 ALL

test_wheel:
  extends: .acc_py_wheel_test
  # Override `script` to adjust the pytest arguments.
  script:
    - mkdir -p ~/not-the-source-dir && cd ~/not-the-source-dir
    - python -m pytest --pyargs ${project_package} --doctest-modules

# Deploy: Publish the wheel on acc-py-repo.cern.ch.

publish:
  extends: .acc_py_publish

# Release: Show the code to the world.

gitlab_release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    name: 'Release $CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
